### PR TITLE
Hotfix - resolve duplicate ol codes in CAID 2

### PR DESCRIPTION
**Pull request by ryanbeard82**
removed single line of code from .bas and updated version numbers for .bas and .frm

### CODE REVIEW

**Comment by ryanbeard82** [comment]
changed the merge target back to master

**Review by AronGahagan — APPROVED** [review]

**Comment by AronGahagan** [comment]
Thanks Ryan! Friendly reminder: for hotfixes and feature updates please branch off of `develop` and please select `develop` as the merge target for pull requests. Also please update both version numbers in CurrentVersions.xml. Sorry to be picky.

Merged and pushed to `master`.

**Comment by ryanbeard82** [comment]
sorry - I do this so infrequently for our repo, and it's managed differently than others I use, might be worth writing down somewhere. The develop branch seemed so far removed from Master, didn't make sense to branch/merge from that one (wasn't sure your plan for rolling other develop changes out).

Something we can discuss at the mtg this week.

**Comment by ryanbeard82** [comment]
If you put a "Pull Request Checklist" in the FAQ, or somewhere in the repot, that'll help me stay in line.

**Comment by ryanbeard82** [comment]
Here's a first cut:


Confirm update urgency with Aron
If needed for out-of-cycle release, branch from Master
If needed for long term release, branch from Develop
Execute module updates
Update the "CurrentVersions.xml" to reflect latest versions of updated modules
Submit Pull Request
Assign Code Reviewers
Tag with appropriate designation (e.g. Bug, Issue #, etc)
Pull Request Approval
Owned by Lead Developer
Review code changes
Verify updates to "CurrentVersions.xml"
Merge into appropriate branch based on release timeline

**Comment by AronGahagan** [comment]
Good idea. I have an issue template I use so I don't forget steps, but I'm probably doing it wrong and am open to being schooled... Again, sorry to be picky.

**Comment by ryanbeard82** [comment]
Is the issue template part of our repo? That would work, but the ones I see are just templates for reporting issues, not steps for repair/release.


Just looking for something to document the additional backbone/core code requirements and the process for hotfix to Master channel vs larger integration into your dev channel. When I looked today, there were over 100 commits on Dev that weren't on Master. Figured this was an easy one to get out quickly and minor enough to pull right from master. Just need to know what your process is and when to use one vs the other, in addition to having something writing down I can look at as a checklist for the ancillary core requirements you wrote that I generally don't interface with (e.g. the XML version file).

**Comment by ryanbeard82** [comment]
Realized I could just create a new pull request template. New branch created and template file added under the .github folder. Branched from Master, but seemed appropriate for this type of change.

**Comment by ryanbeard82** [comment]
Realized I could just create a new pull request template. New branch created and template file added under the .github folder. Branched from Master, but seemed appropriate for this type of change.

**Comment by AronGahagan** [comment]
Yes, the issue template is part of our repo -- but it could use an update. The issue template is available from Issues > New > open a blank issue. But, merging a hotfix to both `develop` and `master` (vs. _everything_ going through `develop` first) looks like it's actually standard/best practice for a good [git process](https://nvie.com/posts/a-successful-git-branching-model/). I think I figured out 'branching in general' early on and never matured beyond that. We should also talk about 100 commit delta b/t develop and master--I'm not seeing that.

**Pull request closed without merging**
